from selenium import webdriver
from  time import  sleep
import  time
dr=webdriver.Firefox()
dr.get('http://www.baidu.com')
dr.find_element_by_id('kw').send_keys('163')
dr.find_element_by_id('su').click()
sleep(2)
dr.find_element_by_xpath('//*[@id="op_email3_username"]').send_keys('zhang15660600605')
sleep(1)
dr.find_element_by_xpath('/html/body/div[1]/div[5]/div[1]/div[3]/div[1]/div[1]/div/form/table/tbody/tr[2]/td[2]/span/input').send_keys('hhxxttxs520')
sleep(1)
dr.find_element_by_xpath('/html/body/div[1]/div[5]/div[1]/div[3]/div[1]/div[1]/div/form/table/tbody/tr[3]/td[2]/a[1]').click()
sleep(1)
a=dr.window_handles
dr.switch_to.window(a[-1])
sleep(5)
dr.switch_to.default_content()
sleep(2)
dr.find_element_by_xpath('//*[@id="_mail_tabitem_1_39"]').click()
sleep(2)
dr.find_element_by_xpath('//*[@id="fly0"]').click()
sleep(2)
dr.find_element_by_xpath('/html/body/div[2]/div[1]/div[2]/header/div/div[2]/div[1]/span').click()
sleep(2)
dr.find_element_by_class_name('nui-ipt-input').click()
sleep(2)
dr.find_element_by_class_name('nui-ipt-input').send_keys('wqe')
sleep(2)
dr.switch_to.default_content()
dr.find_element_by_class_name('kZ0 fu0').click()
sleep(2)
